### ISSUE TITLE
Redirect loop for pdf download from README

### ISSUE THREAD

**Issue by samdengler** [zemirco/nodejs-pdf-docs#7]
When trying to download the pdf version using the URL https://github.com/zemirco/nodejs-pdf-docs/blob/master/pdf/all.pdf?raw=true , I get an error about a redirect loop in Chrome.  I tested the download in curl and the 302 response has the same location as the original request, so I think Chrome is reporting the truth.  Is there something I'm doing wrong?

Thanks!

**Comment by zemirco** [comment]
This is not an issue anymore.
