### ISSUE TITLE
pdf created has no bookmarks

### ISSUE THREAD

**Issue by sunjie21** [zemirco/nodejs-pdf-docs#8]
clone this repo, delete all markdown files, add markdown file from node v4.2.6.
run node app.js, then edit table of contents in pdf/all.tex to include new markdown files and delete non-existing markdown files.
run pdflatex all.tex to create pdf.
pdf has no bookmarks, contents page is blank.
working OS is Ubuntu 14.04 with pandoc and texlive installed.
is there something wrong with my processure? thx.

**Comment by zemirco** [comment]
How do you create the PDF? I mean how do you run LaTeX?

You have to create the PDF twice. First time LaTeX creates the content and stores the ToC. On the second run LaTeX actually writes the Table of Contents.

**Comment by sunjie21** [comment]
1. in root directory of project, run node app.js
2. in pdf directory, edit all.tex table of contents
3. in pdf directory, run pdflatex all.tex

this is my first time to use latex. what do you mean by running latex twice? thx.

**Comment by zemirco** [comment]
You have to open `all.tex` with your favorite editor (i used textmate) and run the latex command. Or start latex from the command line. That's not part of this repository.

**Comment by sunjie21** [comment]
fix it by running latex all.tex after editting table of contents in all.tex, then run pdflatex all.tex. pdf created has proper bookmarks. thx.
